# Copyright (c) 2025 Intel Corporation.
apiVersion: v1
kind: Service
metadata:
  name: coturn
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort  # Exposes the service externally
  selector:
    app: coturn
  ports:
    - name: "coturn-tcp"
      protocol: TCP
      port: {{ $.Values.config.coturn.int.coturn_tcp_port }}
      targetPort: {{ $.Values.config.coturn.int.coturn_tcp_port }}
      nodePort: {{ $.Values.config.coturn.ext.coturn_tcp_port }}  # Exposed on the node
    - name: "coturn-udp"
      protocol: UDP
      port: {{ $.Values.config.coturn.int.coturn_udp_port }}
      targetPort: {{ $.Values.config.coturn.int.coturn_udp_port }}
      nodePort: {{ $.Values.config.coturn.ext.coturn_udp_port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coturn
  name: deployment-coturn
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coturn
  template:
    metadata:
      labels:
        app: coturn
    spec:
      {{- if and .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD }}
      imagePullSecrets:
      - name: registryauth
      {{- end }}
      # hostNetwork: true
      containers:
      - name: coturn
        image: {{ $.Values.coturn.image }}:{{ $.Values.coturn.imageTag }}
        args: ["-v"]  # Enable verbose logging
        ports:
        - containerPort: {{ $.Values.config.coturn.int.coturn_tcp_port }}
          protocol: TCP
        - containerPort: {{ $.Values.config.coturn.int.coturn_udp_port }}
          protocol: UDP
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: http_proxy
          value: {{ $.Values.env.http_proxy }}
        - name: https_proxy
          value: {{ $.Values.env.https_proxy }}
        - name: no_proxy
          value: "{{ $.Values.env.no_proxy }},{{ $.Values.env.HOST_IP }}"
      restartPolicy: Always
