{{- if .Values.mqtt.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nicu-mqtt
  labels:
    {{- include "nicu-warmer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nicu-mqtt
  template:
    metadata:
      labels:
        app: nicu-mqtt
    spec:
      containers:
        - name: nicu-mqtt
          image: "{{ .Values.mqtt.image.repository }}:{{ .Values.mqtt.image.tag }}"
          imagePullPolicy: {{ .Values.mqtt.image.pullPolicy }}
          command: ["mosquitto", "-p", "1883", "-c", "/mosquitto-no-auth.conf"]
          ports:
            - containerPort: 1883
              protocol: TCP
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto-no-auth.conf
              subPath: mosquitto.conf
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 3
            periodSeconds: 5
      volumes:
        - name: mosquitto-config
          configMap:
            name: nicu-mosquitto-config
{{- end }}
