apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.models.claimName }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.uploads.claimName }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: 5Gi
