{{- $serviceType := .Values.service.type | default "ClusterIP" }}

apiVersion: v1
kind: Service
metadata:
  name: nicu-backend
spec:
  type: {{ $serviceType }}
  selector:
    app: nicu-backend
  ports:
    - name: http
      port: 80
      targetPort: 5001
      protocol: TCP
    - name: http-direct
      port: 5001
      targetPort: 5001
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: nicu-ui
spec:
  type: {{ $serviceType }}
  selector:
    app: nicu-ui
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: nicu-metrics-collector
spec:
  type: {{ $serviceType }}
  selector:
    app: nicu-metrics-collector
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP

---
{{- if .Values.dlsps.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nicu-dlsps
spec:
  type: {{ $serviceType }}
  selector:
    app: nicu-dlsps
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
---
{{- end }}

{{- if .Values.mqtt.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nicu-mqtt
spec:
  type: {{ $serviceType }}
  selector:
    app: nicu-mqtt
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
{{- end }}
