---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smart-intersection-pgserver-db
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: smart-intersection
    meta.helm.sh/release-namespace: smart-intersection
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/smart-intersection-pgserver-db

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smart-intersection-pgserver-migrations
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: smart-intersection
    meta.helm.sh/release-namespace: smart-intersection
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/smart-intersection-pgserver-migrations

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smart-intersection-pgserver-media
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: smart-intersection
    meta.helm.sh/release-namespace: smart-intersection
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/smart-intersection-pgserver-media