---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-intersection-pgserver-db
  namespace: smart-intersection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-intersection-pgserver-migrations
  namespace: smart-intersection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-intersection-pgserver-media
  namespace: smart-intersection
  annotations:
    "helm.sh/hook": pre-install
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ri-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi